**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 31, in 03-chapterOutrankingDigraphs.tex
Failed example:
    from perfTabs import RandomPerformanceTableau
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[0]>", line 1, in <module>
        from perfTabs import RandomPerformanceTableau
    ImportError: cannot import name 'RandomPerformanceTableau' from 'perfTabs' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/perfTabs.py)
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 32, in 03-chapterOutrankingDigraphs.tex
Failed example:
    pt = RandomPerformanceTableau(numberOfActions=7,\
                                  seed=100)   
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[1]>", line 1, in <module>
        pt = RandomPerformanceTableau(numberOfActions=7,\
    NameError: name 'RandomPerformanceTableau' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 34, in 03-chapterOutrankingDigraphs.tex
Failed example:
    pt
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[2]>", line 1, in <module>
        pt
    NameError: name 'pt' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 42, in 03-chapterOutrankingDigraphs.tex
Failed example:
    pt.showActions()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[3]>", line 1, in <module>
        pt.showActions()
    NameError: name 'pt' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 59, in 03-chapterOutrankingDigraphs.tex
Failed example:
    pt.showCriteria()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[4]>", line 1, in <module>
        pt.showCriteria()
    NameError: name 'pt' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 86, in 03-chapterOutrankingDigraphs.tex
Failed example:
    pt.showPerformanceTableau()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[5]>", line 1, in <module>
        pt.showPerformanceTableau()
    NameError: name 'pt' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 108, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg = BipolarOutrankingDigraph(pt)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[7]>", line 1, in <module>
        odg = BipolarOutrankingDigraph(pt)
    NameError: name 'pt' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 109, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[8]>", line 1, in <module>
        odg
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 129, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg.showRelationTable()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[9]>", line 1, in <module>
        odg.showRelationTable()
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 158, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg.showPairwiseComparison('a1','a2')
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[10]>", line 1, in <module>
        odg.showPairwiseComparison('a1','a2')
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 178, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg.showPairwiseComparison('a1','a7')
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[11]>", line 1, in <module>
        odg.showPairwiseComparison('a1','a7')
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 200, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg.recodeValuation(-37,+37)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[12]>", line 1, in <module>
        odg.recodeValuation(-37,+37)
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 201, in 03-chapterOutrankingDigraphs.tex
Failed example:
    odg.valuationdomain['hasIntegerValuation'] = True
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[13]>", line 1, in <module>
        odg.valuationdomain['hasIntegerValuation'] = True
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 202, in 03-chapterOutrankingDigraphs.tex
Failed example:
    Digraph.showRelationTable(odg,ReflexiveTerms=False)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[14]>", line 1, in <module>
        Digraph.showRelationTable(odg,ReflexiveTerms=False)
    NameError: name 'Digraph' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 224, in 03-chapterOutrankingDigraphs.tex
Failed example:
    cdodg = -(~odg)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[15]>", line 1, in <module>
        cdodg = -(~odg)
    NameError: name 'odg' is not defined
**********************************************************************
File "03-chapterOutrankingDigraphs.tex", line 225, in 03-chapterOutrankingDigraphs.tex
Failed example:
    cdodg.exportGraphViz('codualOdg')
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 03-chapterOutrankingDigraphs.tex[16]>", line 1, in <module>
        cdodg.exportGraphViz('codualOdg')
    NameError: name 'cdodg' is not defined
**********************************************************************
1 items had failures:
  16 of  17 in 03-chapterOutrankingDigraphs.tex
***Test Failed*** 16 failures.
